language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2

bundler_args: --with development --jobs=9 --retry=2

before_script:
  - sudo apt-get update
  - sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get install -qq graphicsmagick

script:
  - rspec
